version: '3.2'

services:
    tabber:
        image: tabber
        container_name: tabber
        env_file:
            - .env
        ports:
            - "3000:3000"
        volumes:
            -  uploads:/app/uploads

volumes:
    uploads:
