# NOTES:
#   - This Dockerfile is intended for development use and should be used in conjuntion with
#     'docker-compose up --build tabber-dev' to allow live reloading
#      - to begin live reloading, run 'tsc -w' concurrently with this container

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y python3  python3-dbg  python3-pip

# dependencies for crepe
RUN pip3 install -U pip
RUN pip3 install llvmlite==0.34.0
RUN python3 -m pip install librosa

# crepe is run in app like "python3 -m crepe" => install with python3 -m pip
RUN python3 -m pip install crepe
RUN python3 -m pip install --upgrade tensorflow

# used to convert every audio file saved on server to .wav
RUN apt-get install -y ffmpeg

# install nodejs 12, comes packaged with npm 6
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - &&  apt-get install -y nodejs


# must restart when new npm dependencies are added
WORKDIR /app
COPY package*.json /app/
RUN npm install

RUN mkdir /app/crepe

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
