name: tabber

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./server
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: make keys.json
        run: |
          mkdir -p ./keys
          touch ./keys/keys.json
          echo '{ "YOUR_CLIENT_ID": "${{secrets.CLIENT_ID}}", "YOUR_CLIENT_SECRET": "${{secrets.CLIENT_SECRET}}", "YOUR_REDIRECT_URL": "${{secrets.REDIRECT_URL}}", "YOUR_TEST_IDENTITY_TOKEN": "token", "TEST_USER_IDENTITY_TOKEN": "token" }' > ./keys/keys.json

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install dependencies
        run: npm ci

      - name: test
        run: npm test
